# Generated by Django 5.2 on 2025-09-18 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ACCOUNT_CREATED', 'Account created'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('UPDATE_PROFILE', 'profile updated'), ('CHANGE_PASSWORD', 'password changed'), ('UPLOAD_PHOTO', 'profile picture uploaded'), ('DELETE_ACCOUNT', 'account deleted')], max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'action', 'created_at'], name='users_activ_user_id_b220e6_idx')],
            },
        ),
    ]
