# Generated by Django 5.2 on 2025-08-29 12:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journal',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='journal',
            name='category',
        ),
        migrations.AddIndex(
            model_name='journal',
            index=models.Index(fields=['user', '-created_at'], name='journals_jo_user_id_820538_idx'),
        ),
    ]
