# Generated by Django 5.2 on 2025-09-03 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0002_alter_journal_options_remove_journal_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('ai_response', models.TextField(blank=True, null=True)),
                ('sentiment', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='journal',
            name='journals_jo_user_id_820538_idx',
        ),
        migrations.RenameField(
            model_name='journal',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='ai_response',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='content',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='sentiment',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='journal',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='journals.journal'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['journal', '-created_at'], name='journals_jo_journal_4828bb_idx'),
        ),
    ]
