# Generated by Django 5.2 on 2025-09-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0003_journalentry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='journal_covers/'),
        ),
    ]
